language: node_js
node_js:
  - "8"

before_install: cd web/src/frontend

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: gh-pages
  local-dir: web/src/main/webapp
  on:
    branch: feature/github-pages