language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
  - cd v2
  - npm run build
  - cd ..
  - cp -r v2/build/static/js build
  - cp -r v2/build/static/css build
  - ls build
  - ls build/js
  - ls build/css
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
