language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
    - v2/node_modules
script:
  - npm run build
  - npm test
  - cd v2
  - npm ci
  - npm run build
  - cd ..
  - cp -r v2/build build/v2
  - ls build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
