language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: maste
